spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapo_tofu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
